package de.mkn.training.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * A training plan generated by the DICE feature.
 * Captures the user's intent (subject + total duration) and the resulting
 * ordered list of exercises.
 */
@Entity
@Table(name = "exercise_plans")
public class ExercisePlan {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumn(name = "subject_id")
    private Subject subject;

    /** Total training time the user requested (minutes). */
    @Column(nullable = false)
    private Integer requestedDurationMinutes;

    @Column(nullable = false)
    private LocalDateTime createdAt = LocalDateTime.now();

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private PlanStatus status = PlanStatus.PENDING;

    @OneToMany(mappedBy = "plan", cascade = CascadeType.ALL, orphanRemoval = true)
    @OrderBy("orderIndex ASC")
    private List<ExercisePlanItem> items = new ArrayList<>();

    protected ExercisePlan() {}

    public ExercisePlan(Subject subject, Integer requestedDurationMinutes) {
        this.subject = subject;
        this.requestedDurationMinutes = requestedDurationMinutes;
    }

    public void addItem(ExercisePlanItem item) {
        item.setPlan(this);
        items.add(item);
    }

    // --- Getters & Setters ---

    public Long getId() { return id; }

    public Subject getSubject() { return subject; }
    public void setSubject(Subject subject) { this.subject = subject; }

    public Integer getRequestedDurationMinutes() { return requestedDurationMinutes; }
    public void setRequestedDurationMinutes(Integer requestedDurationMinutes) {
        this.requestedDurationMinutes = requestedDurationMinutes;
    }

    public LocalDateTime getCreatedAt() { return createdAt; }

    public PlanStatus getStatus() { return status; }
    public void setStatus(PlanStatus status) { this.status = status; }

    public List<ExercisePlanItem> getItems() { return items; }
}
